import { router } from 'expo-router';
import { ScrollView, StyleSheet, Text, View, Pressable } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { games, getNextGame } from '@/games/registry';
import { Header, palette, PrimaryButton } from '@/ui/screen';

export default function GameLibraryRoute() {
  const startQuickMix = () => router.replace(`/play/game/${getNextGame().id}?session=quick`);
  return <SafeAreaView style={styles.safe} edges={['top']}><Header title="Play together" onBack={() => router.back()} /><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.title}>Let the game pick.</Text><Text style={styles.copy}>Start a quick mix and get a different tiny co-op game every round. No planning needed.</Text><View style={styles.quickCard}><Text style={styles.quickEmoji}>🎲</Text><View style={styles.quickWords}><Text style={styles.quickTitle}>Quick mix</Text><Text style={styles.quickCopy}>Random games · 3–5 min</Text></View></View><PrimaryButton label="Start a surprise" onPress={startQuickMix} /><Text style={styles.section}>Or pick a favorite</Text><View style={styles.grid}>{games.map((game) => <Pressable key={game.id} accessibilityRole="button" onPress={() => router.push(`/play/game/${game.id}`)} style={({ pressed }) => [styles.card, { backgroundColor: game.color }, pressed && styles.pressed]}><Text style={styles.emoji}>{game.emoji}</Text><Text style={styles.cardTitle}>{game.title}</Text><Text style={styles.cardCopy}>{game.subtitle}</Text><Text style={styles.duration}>{game.duration}  →</Text></Pressable>)}</View></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: palette.cream }, content: { padding: 20, paddingTop: 10, paddingBottom: 40 }, title: { color: palette.ink, fontSize: 31, fontWeight: '900', letterSpacing: -1.2 }, copy: { color: palette.muted, fontSize: 14, lineHeight: 20, marginTop: 8, marginBottom: 23, maxWidth: 320 }, quickCard: { backgroundColor: '#E8DFFF', borderRadius: 22, padding: 17, flexDirection: 'row', alignItems: 'center', gap: 13, marginBottom: 13 }, quickEmoji: { fontSize: 37 }, quickWords: { flex: 1 }, quickTitle: { color: palette.ink, fontSize: 17, fontWeight: '900' }, quickCopy: { color: palette.muted, fontSize: 12, marginTop: 4 }, section: { color: palette.ink, fontSize: 18, fontWeight: '900', marginTop: 29, marginBottom: 13 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, card: { width: '48.2%', minHeight: 161, padding: 15, borderRadius: 21, borderWidth: 1, borderColor: '#FFFFFF' }, emoji: { color: palette.ink, fontSize: 31, fontWeight: '900' }, cardTitle: { color: palette.ink, fontSize: 15, fontWeight: '900', marginTop: 14 }, cardCopy: { color: palette.muted, fontSize: 11, lineHeight: 15, marginTop: 4 }, duration: { color: palette.ink, fontSize: 10, fontWeight: '900', marginTop: 'auto' }, pressed: { opacity: .78, transform: [{ scale: .97 }] } });
